### PR TITLE
try for card_fun

### LINKED ISSUE #86: try/catch evaluation of the Card Fun
We need to use the try clause for the card_fun evaluation and if failed print the proper error message.

### PR DESCRIPTION
**Pull request by Polkas**
closes #86 

This should give the end user a proper message when the card_fun is not evaluated properly.
The modal is not closed automatically on purpose, we are sure sb read the message (bottom right).

### CODE REVIEW

File: R/AddCardModule.R [hunk 1]
```diff
@@ -110,19 +110,35 @@ add_card_button_srv <- function(id, reporter, card_fun) {
...
+              card$append_text("Comment", "header3")
+              card$append_text(input$comment)
+            }
           }
+        }
+
+        if (inherits(card, "try-error")) {
+          msg <- paste0(
+            "The card was not added successfully.",
+            "Possibly the card_fun is invalid or the shiny process is not ready to be catched."
```
Comment (nikolas-burkoff) [inline R/AddCardModule.R:129]:
```suggestion
            "The card could not be added to the report. ",
            "Have the outputs for the report been created yet? If not please try again when they ",
            "are ready. Otherwise contact your application developer" 
```

**Review by nikolas-burkoff — APPROVED** [review]
Looks good - a couple of minor wording tweaks but this can then go in
